# 
# ## Welcome in the Balls of Steel configuration file ##
# 
# 
# About the "sound" configuration, the format is always the same:
# sound:
#     name:   The name of the sound. Names: see http://l.carrade.eu/bukkit-sounds . Set to "NONE" to disable.
#     volume: The volume of the sound. 1 is the normal volume. You can use a decimal value.
#     pitch:  The pitch of the sound.  1 is the normal pitch.  You can use a decimal value.
# 


# Available languages: en_US, fr_FR, pt_PT.
lang: en_US



start:        
    sound:
        name: NONE
        volume: 1
        pitch: 1



# If true, the name of the players will be colorized according to the teams.
colorizeChat: true



teams-options:
    canSeeFriendlyInvisibles: true
    allowFriendlyFire: true
    
    # 0 = unlimited.
    maxPlayersPerTeam: 0



# Controls the behavior of the /bos finish command
finish:
    auto:
        do: true  # Execute /bos finish automatically a few seconds after the end of the game?
        timeAfterEnd: 3  # The command will be executed this amount of seconds after the last death.
    
    message: true  # If true, the name of the winner(s) will be broadcasted.
    fireworks:
        enabled: true  # If true, some fireworks will be launched at the location of the winners.
        duration: 10   # In seconds.
        areaSize: 6    # The size of the square, centered on each player, where the fireworks will be launched.



# Log the private team-chat in the console?
logTeamChat: false



# Use this to pre-register the teams.
# Format:
#     - color
#  -- OR --
#     - color,name

teams:
    -
