# 
# ## Welcome in the Balls of Steel configuration file ##
# 
# 
# About the "sound" configuration, the format is always the same:
# sound:
#     name:   The name of the sound. Names: see http://l.carrade.eu/bukkit-sounds . Set to "NONE" to disable.
#     volume: The volume of the sound. 1 is the normal volume. You can use a decimal value.
#     pitch:  The pitch of the sound.  1 is the normal pitch.  You can use a decimal value.
# 


# Available languages: en_US, fr_FR.
lang: en_US



# The game name displayed in the sidebar
gameName: "Balls of Steel"



# The duration of the game.
# Format: "mm", "mm:ss" or "hh:mm:ss".
duration: "59:59"



# Use the boss bar to display the time left of the game, and the winners?
bar:
    enabled: true

    # The bar title displayed (can include colors)
    title: "Balls of Steel"

    # If true, the title is displayed alongside the timer during the game. Else, only before.
    displayTitleDuringGame: false

    # Bars colors: pink, blue, red, green, yellow, purple, white.
    # Bars styles: solid, segmented_6, segmented_10, segmented_12, segmented_20.
    barColorBeforeGame: YELLOW
    barStyleBeforeGame: SOLID
    barColorDuringGame: YELLOW
    barColorCloseToEnd: RED
    barStyleDuringGame: SEGMENTED_6

    # The time left percentage used to determine if we are close to the end (and use the appropriate color).
    # Between 0 and 1; 0.1 means we use the close to end color if less than 10% of the time is left (e.g. for one hour,
    # 6 minutes left).
    closeToEndPercentage: 0.167



# The name of the folder containing the map generation rules.
map_config: "default"



start:
    sound:
        name: NONE
        volume: 1
        pitch: 1



diamonds:
    sounds:
        # Played when a team place some diamonds in the chest
        countIncrease:
            name: ENTITY_ARROW_HIT_PLAYER
            volume: 1
            pitch: 3
        
        # Played when a team take some diamonds from the chest
        countDecrease:
            name: NONE
            volume: 1
            pitch: 0.2

        # Played when someone try to access another team chest (to himself only)
        chestLocked:
            name: BLOCK_CHEST_LOCKED
            volume: 2
            pitch: 1



# This is given to the player when the game start and when they respawn.
equipment:
    food: true      # 1 stack of steaks
    blocks: true    # 2 stacks of dirt blocks
    tools: true     # pickaxe, axe, shovel
    sword: false    # sword
    bow: true       # infinity bow, one arrow
    armor: "none"   # "none", "weak" (leather), "normal" (chainmail), "strong" (iron) or "very strong" (diamond).

    # If true, all the enabled equipments above will be given only if they were built
    # in survival before (foods and blocks excepted).
    survivalMode: false

    # If true, players will, as example, unlock the pickaxe with any pickaxe crafted.
    # If false, only with an iron pickaxe. The same for any other tool (if relevant).
    unlockWithAnyMaterial: false

    # If true, tools given enchanted will be enchanted when crafted.
    # Also, if this is true, players will receive an arrow while crafing a bow.
    craftEnchanted: true



# If true, the name of the players will be colorized according to the teams.
colorizeChat: true



teams-options:
    canSeeFriendlyInvisibles: true
    allowFriendlyFire: true
    
    # 0 = unlimited.
    maxPlayersPerTeam: 0



# Controls the behavior of the /bos finish command
finish:
    auto:
        do: true  # Execute /bos finish automatically a few seconds after the end of the game?
        timeAfterEnd: 3  # The command will be executed this amount of seconds after the last death.
    
    message: true  # If true, the name of the winner(s) will be broadcasted.
    fireworks:
        enabled: true  # If true, some fireworks will be launched at the location of the winners.
        duration: 10   # In seconds.
        areaSize: 6    # The size of the square, centered on each player, where the fireworks will be launched.



# Log the private team-chat in the console?
logTeamChat: false



# Use this to pre-register the teams.
# Format:
#     - color
#  -- OR --
#     - color,name

teams:
    -
