name: BallsOfZirconium
description: Balls of Zirconium, a modernized Balls of Steel game with automated generation
main: eu.carrade.amaury.ballsofzirconium.BallsOfZirconium
version: 0.1 §cdev§r
author: "Amaury Carrade"
api-version: "1.15"

load: STARTUP

softdepend:
  - WorldEdit

commands:
   boz:
      description: Balls of Zirconium base command

   t:
      description: Allows an user to send a message to his team.
      usage: /t <message>
   
   g:
      description: Allows an user to send a message to everyone.
      usage: /g <message>
   
   togglechat:
       description: Allows an user to toggle the chat between the global chat and a team chat.
       usage: /togglechat

permissions:
    
